spring.application.name=backend

spring.datasource.url=jdbc:sqlite:./data/hearforthevibes.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
spring.jpa.hibernate.ddl-auto=update